local Maps = {
	
	

	
	["Tropical Island"] = {
		
		MapFolder = game.ServerStorage:WaitForChild("Tropical Island"),
		Name = "Tropical Island",
		VotingImage = "rbxassetid://70452409071350"
		
	},
	
	
	["Cargo Port"] = {

		MapFolder = game.ServerStorage:WaitForChild("Cargo Port"),
		Name = "Cargo Port",
		VotingImage = "rbxassetid://80627568706730"

	},
	
	
	["Farm"] = {

		MapFolder = game.ServerStorage:WaitForChild("Farm"),
		Name = "Farm",
		VotingImage = "rbxassetid://127578255823149"

	},
	
	["Grids"] = {

		MapFolder = game.ServerStorage:WaitForChild("Grids"),
		Name = "Grids",
		VotingImage = "rbxassetid://82181977781980"

	},

	
	
	
	
	


	
	
}

return Maps
