local Maps = {
	
	

	
	["Tropical Island"] = {
		
		MapFolder = game.ServerStorage:WaitForChild("Tropical Island"),
		Name = "Tropical Island",
		VotingImage = "rbxassetid://70452409071350",
		ResultsImage = "rbxassetid://134309678506763"
		
	},
	
	
	["Cargo Port"] = {

		MapFolder = game.ServerStorage:WaitForChild("Cargo Port"),
		Name = "Cargo Port",
		VotingImage = "rbxassetid://80627568706730",
		ResultsImage = "rbxassetid://110373121452497"

	},
	
	
	
	["Grids"] = {

		MapFolder = game.ServerStorage:WaitForChild("Grids"),
		Name = "Grids",
		VotingImage = "rbxassetid://82181977781980",
		ResultsImage = "rbxassetid://71138965019130"

	},
	
	
	["Classic ROBLOX"] = {

		MapFolder = game.ServerStorage:WaitForChild("Classic ROBLOX"),
		Name = "Classic ROBLOX",
		VotingImage = "rbxassetid://83806131745447",
		ResultsImage = "rbxassetid://134969036195314"

	},

	
	
	
	
	


	
	
}

return Maps
