return {
	["emote1"] = {
		Rarity = "Legendary",
		EmoteId = "rbxassetid://98351745309102",
		EmoteName = "Shot me out of the sky"

	} , 


	["Godly Dance"] = {
		Rarity = "Godly",
		EmoteId = "rbxassetid://118637453055054",
		EmoteName = "Godly Dance"

	} , 



	["Sit"] = {
		Rarity = "Common",
		EmoteId = "rbxassetid://73124046055757",
		EmoteName = "Sit"

	} ,



	["Griddy"] = {
		Rarity = "Rare",
		EmoteId = "rbxassetid://76631481904394",
		EmoteName = "Griddy"

	} , 






}
