return {
	["emote1"] = {
		Rarity = "Legendary",
		EmoteId = "rbxassetid://98351745309102",
		EmoteName = "Shot me out of the sky"

	} , 


	["emote2"] = {
		Rarity = "Godly",
		EmoteId = "rbxassetid://118637453055054",
		EmoteName = "Cool dance"

	} , 


	["emote3"] = {
		Rarity = "Common",
		EmoteId = "rbxassetid://73124046055757",
		EmoteName = "Sit Emote"

	} ,


	["Griddy"] = {
		Rarity = "Rare",
		EmoteId = "rbxassetid://76631481904394",
		EmoteName = "Griddy"

	} , 






}
