return {

	["Bowie"] = {
		MeshId = "rbxassetid://76151122138295";
		Image = "rbxassetid://128915035739702"; 
		Rarity = "Common"
	};
	["Shadow Dagger"] = {
		MeshId = "rbxassetid://125221819012837";
		Image = "rbxassetid://136446725670672"; 
		Rarity = "Common"
	};
	["Gut Knife"] = {
		MeshId = "rbxassetid://77763749038032";
		Image = "rbxassetid://94733020530911"; 
		Rarity = "Common"
	};
	["Karambit"] = {
		MeshId = "rbxassetid://74098031379543";
		Image = "rbxassetid://117139977173647";
		Rarity = "Rare"
	};


	["Huntsman"] = {
		MeshId = "rbxassetid://76151122138295";
		Image = "rbxassetid://110090371443131"; 
		Rarity = "Rare"
	};
	["Flip"] = {
		MeshId = "rbxassetid://125221819012837";
		Image = "rbxassetid://131414680575050";
		Rarity = "Rare"
	};
	["Skeleton"] = {
		MeshId = "rbxassetid://77763749038032";
		Image = "rbxassetid://117258497744746"; 
		Rarity = "Epic"
	};
	["Butterfly"] = {
		MeshId = "rbxassetid://74098031379543";
		Image = "rbxassetid://97175454317266"; 
		Rarity = "Epic"
	};

	["Bayonet"] = {
		MeshId = "rbxassetid://125221819012837";
		Image = "rbxassetid://87524479567401"; 
		Rarity = "Legendary"
	};
	["Frostbite"] = {
		MeshId = "rbxassetid://77763749038032";
		Image = "rbxassetid://131938644607549"; 
		Rarity = "Godly"
	};


	["Ethereal"] = {
		MeshId = "rbxassetid://94327609424355";
		Image = "rbxassetid://88521515119416"; 
		Rarity = "Godly"
	};



}
