return {

	["Bowie"] = {
		MeshId = "rbxassetid://76151122138295";
		Image = "rbxassetid://79387416444978"; 
		Rarity = "Common"
	};
	["Shadow Dagger"] = {
		MeshId = "rbxassetid://125221819012837";
		Image = "rbxassetid://101079332785214"; 
		Rarity = "Common"
	};
	["Gut Knife"] = {
		MeshId = "rbxassetid://77763749038032";
		Image = "rbxassetid://74998097772229"; 
		Rarity = "Common"
	};
	["Karambit"] = {
		MeshId = "rbxassetid://74098031379543";
		Image = "rbxassetid://94623740577139";
		Rarity = "Rare"
	};


	["Huntsman"] = {
		MeshId = "rbxassetid://76151122138295";
		Image = "rbxassetid://130250884414828"; 
		Rarity = "Rare"
	};
	["Flip"] = {
		MeshId = "rbxassetid://125221819012837";
		Image = "rbxassetid://113796553871343";
		Rarity = "Rare"
	};
	["Skeleton"] = {
		MeshId = "rbxassetid://77763749038032";
		Image = "rbxassetid://80404477033105"; 
		Rarity = "Epic"
	};
	["Butterfly"] = {
		MeshId = "rbxassetid://74098031379543";
		Image = "rbxassetid://123885588812042"; 
		Rarity = "Epic"
	};

	["Bayonet"] = {
		MeshId = "rbxassetid://125221819012837";
		Image = "rbxassetid://123396569142363"; 
		Rarity = "Legendary"
	};
	["Frostbite"] = {
		MeshId = "rbxassetid://77763749038032";
		Image = "rbxassetid://84525386784595"; 
		Rarity = "Godly"
	};

}
