local RevolversInfo = {
	["Amber Revolver"] = {
		Rarity = "Rare",
		Image = "rbxassetid://83454723285678",
		tradeable = true,
	},
	["Aurum Revolver"] = {
		Rarity = "Rare",
		Image = "rbxassetid://81529050474557",
		tradeable = true,
	},
	["Azure Revolver"] = {
		Rarity = "Rare",
		Image = "rbxassetid://112864017586213",
		tradeable = true,
	},
	["Berserk Revolver"] = {
		Rarity = "Rare",
		Image = "rbxassetid://99425352586097",
		tradeable = true,
	},
	["Blaze Revolver"] = {
		Rarity = "Legendary",
		Image = "rbxassetid://104580526333984",
		tradeable = true,
	},
	["Blossom Revolver"] = {
		Rarity = "Epic",
		Image = "rbxassetid://73856803252142",
		tradeable = true,
	},
	["Camo Revolver"] = {
		Rarity = "Epic",
		Image = "rbxassetid://99125612862390",
		tradeable = true,
	},
	["Cosmic Revolver"] = {
		Rarity = "Epic",
		Image = "rbxassetid://93732041073339",
		tradeable = true,
	},
	["Crimson Revolver"] = {
		Rarity = "Legendary",
		Image = "rbxassetid://99270174970408",
		tradeable = true,
	},
	["Divine Revolver"] = {
		Rarity = "Legendary",
		Image = "rbxassetid://91362422823769",
		tradeable = true,
	},
	["Dragon Scale Revolver"] = {
		Rarity = "Legendary",
		Image = "rbxassetid://77672216366653",
		tradeable = true,
	},
	["Frostbite Revolver"] = {
		Rarity = "Rare",
		Image = "rbxassetid://138081147953970",
		tradeable = true,
	},
	["Glacial Revolver"] = {
		Rarity = "Rare",
		Image = "rbxassetid://83710095500259",
		tradeable = true,
	},
	["Grim Revolver"] = {
		Rarity = "Epic",
		Image = "rbxassetid://133591246590889",
		tradeable = true,
	},
	["Hellfire Revolver"] = {
		Rarity = "Legendary",
		Image = "rbxassetid://83746029455447",
		tradeable = true,
	},
	["Honeyed Revolver"] = {
		Rarity = "Rare",
		Image = "rbxassetid://120383135012006",
		tradeable = true,
	},
	["Inferno Revolver"] = {
		Rarity = "Legendary",
		Image = "rbxassetid://98315570234572",
		tradeable = true,
	},
	["Jade Revolver"] = {
		Rarity = "Legendary",
		Image = "rbxassetid://89409331668745",
		tradeable = true,
	},
	["Love Train Revolver"] = {
		Rarity = "Godly",
		Image = "rbxassetid://85219009699523",
		tradeable = true,
	},
	["Mysterious Revolver"] = {
		Rarity = "Legendary",
		Image = "rbxassetid://98357252407514",
		tradeable = true,
	},
	["Mystic Revolver"] = {
		Rarity = "Epic",
		Image = "rbxassetid://136683987588404",
		tradeable = true,
	},
	["Nebula Revolver"] = {
		Rarity = "Epic",
		Image = "rbxassetid://121036803561654",
		tradeable = true,
	},
	["Normal Revolver"] = {
		Rarity = "Common",
		Image = "rbxassetid://116387669826367",
		tradeable = true,
	},
	["Onyx Revolver"] = {
		Rarity = "Rare",
		Image = "rbxassetid://86599473520381",
		tradeable = true,
	},
	["Permafrost Revolver"] = {
		Rarity = "Legendary",
		Image = "rbxassetid://77353394722329",
		tradeable = true,
	},
	["Phantom Revolver"] = {
		Rarity = "Godly",
		Image = "rbxassetid://132811507981856",
		tradeable = true,
	},
	["Radiant Revolver"] = {
		Rarity = "Epic",
		Image = "rbxassetid://97515742262669",
		tradeable = true,
	},
	["Winter Revolver 2"] = {
		Rarity = "Legendary",
		Image = "rbxassetid://124991966450034",
		tradeable = true,
	},
	["Winter Revolver"] = {
		Rarity = "Legendary",
		Image = "rbxassetid://73585459412001",
		tradeable = true,
	},
	["Void Revolver"] = {
		Rarity = "Legendary",
		Image = "rbxassetid://113892346254233",
		tradeable = true,
	},
	["Vermilion Revolver"] = {
		Rarity = "Godly",
		Image = "rbxassetid://103818079006111",
		tradeable = true,
	},
	["Verdant Revolver"] = {
		Rarity = "Epic",
		Image = "rbxassetid://113526030614414",
		tradeable = true,
	},
	["Venom Revolver"] = {
		Rarity = "Epic",
		Image = "rbxassetid://137746854597295",
		tradeable = true,
	},
	["Umbra Revolver"] = {
		Rarity = "Legendary",
		Image = "rbxassetid://81848899919416",
		tradeable = true,
	},
	["Twilight Revolver"] = {
		Rarity = "Epic",
		Image = "rbxassetid://114189530647947",
		tradeable = true,
	},
	["Toxic Revolver"] = {
		Rarity = "Epic",
		Image = "rbxassetid://138274944344501",
		tradeable = true,
	},
	["Tidal Revolver"] = {
		Rarity = "Epic",
		Image = "rbxassetid://132075884554589",
		tradeable = true,
	},
	["Tempest Revolver"] = {
		Rarity = "Legendary",
		Image = "rbxassetid://98955528405670",
		tradeable = true,
	},
	["Sylvan Revolver"] = {
		Rarity = "Epic",
		Image = "rbxassetid://112600193939840",
		tradeable = true,
	},
	["Sterling Revolver"] = {
		Rarity = "Epic",
		Image = "rbxassetid://127007055298014",
		tradeable = true,
	},
	["Steampunk Revolver"] = {
		Rarity = "Epic",
		Image = "rbxassetid://122292159598407",
		tradeable = true,
	},
	["Spectral Revolver"] = {
		Rarity = "Legendary",
		Image = "rbxassetid://93793548250978",
		tradeable = true,
	},
	["Shattered Revolver"] = {
		Rarity = "Legendary",
		Image = "rbxassetid://124569988193879",
		tradeable = true,
	},
	["Seraph Revolver"] = {
		Rarity = "Epic",
		Image = "rbxassetid://107807004812074",
		tradeable = true,
	},
	["Scarlet Revolver"] = {
		Rarity = "Legendary",
		Image = "rbxassetid://89833127324076",
		tradeable = true,
	},
	["Sapphire Revolver"] = {
		Rarity = "Epic",
		Image = "rbxassetid://110207253929227",
		tradeable = true,
	},
	["Royal Revolver"] = {
		Rarity = "Legendary",
		Image = "rbxassetid://102883609368171",
		tradeable = true,
	},
	["Abyssal Tide Revolver"] = {
		Rarity = "Godly",
		Image = "rbxassetid://127318809058935",
		tradeable = true,
	},
	["Bubble Gun Revolver"] = {
		Rarity = "Godly",
		Image = "rbxassetid://128616795998485",
		tradeable = true,
	},
	["White&Black Revolver"] = {
		Rarity = "Common",
		Image = "rbxassetid://88474215654699",
		tradeable = false,
	},
	["Arcane Revolver"] = {
		Rarity = "Legendary",
		Image = "rbxassetid://137653621843098",
		tradeable = true,
	},
	["Amethyst Revolver"] = {
		Rarity = "Legendary",
		Image = "rbxassetid://101357381715369",
		tradeable = true,
	},
}

return RevolversInfo
