local RevolversInfo = {
	["Amber Revolver"] = {
		Rarity = "",
		Image = "rbxassetid://110476285948091",
		Tradeable = false,
	},
	["Aurum Revolver"] = {
		Rarity = "",
		Image = "rbxassetid://127204321738957",
		Tradeable = false,
	},
	["Azure Revolver"] = {
		Rarity = "",
		Image = "rbxassetid://84470632166898",
		Tradeable = false,
	},
	["Berserk Revolver"] = {
		Rarity = "",
		Image = "rbxassetid://101037810272221",
		Tradeable = false,
	},
	["Blaze Revolver"] = {
		Rarity = "",
		Image = "rbxassetid://105665144326585",
		Tradeable = false,
	},
	["Blossom Revolver"] = {
		Rarity = "",
		Image = "rbxassetid://92721193596430",
		Tradeable = false,
	},
	["Camo Revolver"] = {
		Rarity = "",
		Image = "rbxassetid://82781788414078",
		Tradeable = false,
	},
	["Cosmic Revolver"] = {
		Rarity = "",
		Image = "rbxassetid://115399230796447",
		Tradeable = false,
	},
	["Crimson Revolver"] = {
		Rarity = "",
		Image = "rbxassetid://75343589737255",
		Tradeable = false,
	},
	["Divine Revolver"] = {
		Rarity = "",
		Image = "rbxassetid://133856379478905",
		Tradeable = false,
	},
	["Dragon Scale Revolver"] = {
		Rarity = "",
		Image = "rbxassetid://121578477866640",
		Tradeable = false,
	},
	["Frostbite Revolver"] = {
		Rarity = "",
		Image = "rbxassetid://82807003201855",
		Tradeable = false,
	},
	["Glacial Revolver"] = {
		Rarity = "",
		Image = "rbxassetid://126027048691915",
		Tradeable = false,
	},
	["Grim Revolver"] = {
		Rarity = "",
		Image = "rbxassetid://75137040862632",
		Tradeable = false,
	},
	["Hellfire Revolver"] = {
		Rarity = "",
		Image = "rbxassetid://117686224732951",
		Tradeable = false,
	},
	["Honeyed Revolver"] = {
		Rarity = "",
		Image = "rbxassetid://95600252178640",
		Tradeable = false,
	},
	["Inferno Revolver"] = {
		Rarity = "",
		Image = "rbxassetid://81967364677532",
		Tradeable = false,
	},
	["Jade Revolver"] = {
		Rarity = "",
		Image = "rbxassetid://123165836493113",
		Tradeable = false,
	},
	["Love Train Revolver"] = {
		Rarity = "",
		Image = "rbxassetid://79832044170964",
		Tradeable = false,
	},
	["Mysterious Revolver"] = {
		Rarity = "",
		Image = "rbxassetid://80874360908241",
		Tradeable = false,
	},
	["Mystic Revolver"] = {
		Rarity = "",
		Image = "rbxassetid://119207610976864",
		Tradeable = false,
	},
	["Nebula Revolver"] = {
		Rarity = "",
		Image = "rbxassetid://124323101308183",
		Tradeable = false,
	},
	["Normal Revolver"] = {
		Rarity = "",
		Image = "rbxassetid://73555594692861",
		Tradeable = false,
	},
	["Onyx Revolver"] = {
		Rarity = "",
		Image = "rbxassetid://120557027496696",
		Tradeable = false,
	},
	["Permafrost Revolver"] = {
		Rarity = "",
		Image = "rbxassetid://91479297835594",
		Tradeable = false,
	},
	["Phantom Revolver"] = {
		Rarity = "",
		Image = "rbxassetid://137942577456945",
		Tradeable = false,
	},
	["Radiant Revolver"] = {
		Rarity = "",
		Image = "rbxassetid://81337171640206",
		Tradeable = false,
	},
	["Winter Revolver 2"] = {
		Rarity = "",
		Image = "rbxassetid://73399240931507",
		Tradeable = false,
	},
	["Winter Revolver"] = {
		Rarity = "",
		Image = "rbxassetid://88793143864258",
		Tradeable = false,
	},
	["Void Revolver"] = {
		Rarity = "",
		Image = "rbxassetid://136706692206525",
		Tradeable = false,
	},
	["Vermilion Revolver"] = {
		Rarity = "",
		Image = "rbxassetid://138392890124441",
		Tradeable = false,
	},
	["Verdant Revolver"] = {
		Rarity = "",
		Image = "rbxassetid://93356224060846",
		Tradeable = false,
	},
	["Venom Revolver"] = {
		Rarity = "",
		Image = "rbxassetid://78829794055719",
		Tradeable = false,
	},
	["Umbra Revolver"] = {
		Rarity = "",
		Image = "rbxassetid://104185218884798",
		Tradeable = false,
	},
	["Twilight Revolver"] = {
		Rarity = "",
		Image = "rbxassetid://118430420645704",
		Tradeable = false,
	},
	["Toxic Revolver"] = {
		Rarity = "",
		Image = "rbxassetid://116980367564599",
		Tradeable = false,
	},
	["Tidal Revolver"] = {
		Rarity = "",
		Image = "rbxassetid://110446720795326",
		Tradeable = false,
	},
	["Tempest Revolver"] = {
		Rarity = "",
		Image = "rbxassetid://122625559205058",
		Tradeable = false,
	},
	["Sylvan Revolver"] = {
		Rarity = "",
		Image = "rbxassetid://96224392882886",
		Tradeable = false,
	},
	["Sterling Revolver"] = {
		Rarity = "",
		Image = "rbxassetid://107446380128890",
		Tradeable = false,
	},
	["Steampunk Revolver"] = {
		Rarity = "",
		Image = "rbxassetid://86534208201346",
		Tradeable = false,
	},
	["Spectral Revolver"] = {
		Rarity = "",
		Image = "rbxassetid://71989409405920",
		Tradeable = false,
	},
	["Shattered Revolver"] = {
		Rarity = "",
		Image = "rbxassetid://109902029461771",
		Tradeable = false,
	},
	["Seraph Revolver"] = {
		Rarity = "",
		Image = "rbxassetid://96016564526509",
		Tradeable = false,
	},
	["Scarlet Revolver"] = {
		Rarity = "",
		Image = "rbxassetid://78548402577979",
		Tradeable = false,
	},
	["Sapphire Revolver"] = {
		Rarity = "",
		Image = "rbxassetid://140556404628331",
		Tradeable = false,
	},
	["Royal Revolver"] = {
		Rarity = "",
		Image = "rbxassetid://84030708997229",
		Tradeable = false,
	},
	["Abyssal Tide Revolver"] = {
		Rarity = "",
		Image = "rbxassetid://102121921175047",
		Tradeable = false,
	},
	["Bubble Gun Revolver"] = {
		Rarity = "",
		Image = "rbxassetid://103086757817235",
		Tradeable = false,
	},
	["White&Black Revolver"] = {
		Rarity = "",
		Image = "rbxassetid://116755830178179",
		Tradeable = false,
	},
	["Arcane Revolver"] = {
		Rarity = "",
		Image = "rbxassetid://123145907322142",
		Tradeable = false,
	},
	["Amethyst Revolver"] = {
		Rarity = "",
		Image = "rbxassetid://92304100649386",
		Tradeable = false,
	},
}

return RevolversInfo
