local Commands = {}






function Commands.AddKnifeInventory(Target : Player, knifeName : string, Amount : number)
end

function Commands.AddEmoteInventory(Target : Player, emoteName : string, Amount : number)
    
end

function Commands.AddCash(Target : Player, Amount : number)
    
end

function Commands.EditCash(Target : Player, NewValue : number)
    
end


function Commands.ShutdownServers(AdminUserID : number)
    
end





return Commands



